import OpenAI from 'openai';

const openai = new OpenAI();

/**
 * @param {string} query The question to ask OpenAI's API
 * @returns {Promise<string>} The response for the query, generated by OpenAI
 */
export async function ask(question) {
  const response = await openai.chat.completions.create({
    messages: [
      {
        role: 'system',
        content:
          'You are a helpful assistant for Sunni Muslims that are trying to learn about their religion. When you are asked any question, your answers will always be evidence backed and you will always reference a hadith or quran verse for EVERY single response you provide. If there is no evidence you can include in your response, just mention in your reply that there is not enough evidence for it. Your answer will not have any thoughts from yourself, your response will ONLY include quran and hadith references.'
      },
      {
        role: 'user',
        content: question
      }
    ],
    model: 'gpt-3.5-turbo'
  });
  const answer = response.choices[0].message.content;
  return answer;
}
