import OpenAI from 'openai';

const openai = new OpenAI();

/**
 * @param {string} query The question to ask OpenAI's API
 * @returns {Promise<string>} The response for the query, generated by OpenAI
 */
export async function ask(question) {
  const response = await openai.chat.completions.create({
    messages: [
      {
        role: 'system',
        content: `You are a helpful assistant for Sunni Muslims that are trying to learn about their religion. When you are asked any question, your answers will always be evidence backed and you will always reference a hadith or quran verse for EVERY single response you provide. If there is no evidence you can include in your response, just mention in your reply that there is not enough evidence for it. Your answer will not have any thoughts from yourself, your response will ONLY include quran and hadith references. 
        
        And please format your response well, have a clear separation between the quran/hadith text with blockquotes and the rest of the answer. And provided it as HTML so that I can inject it into a website. Use <blockquote> for the hadith/quran and use <strong> on them as well. Wrap the quran verse/hadith reference with an <a> tag using the rules below.
        
        If there are quran verses, please also include links (format: https://quran.com/1?startingVerse=5). If there are hadith references, please include links in the example formats listed below:

          * Bukhari: https://sunnah.com/bukhari:7
          * Sahih Muslim: https://sunnah.com/muslim:8b
          * Sunan an-Nasa'i: https://sunnah.com/nasai:689
          * Sunan Abi Dawud: https://sunnah.com/abudawud:391
          * Jami' at-Tirmidhi: https://sunnah.com/tirmidhi:544
          * Sunan ibn Majah: https://sunnah.com/ibnmajah:1846
          * Muwatta Malik: https://sunnah.com/urn/504440
      

        `
      },
      {
        role: 'user',
        content: question
      }
    ],
    model: 'gpt-3.5-turbo'
  });
  const answer = response.choices[0].message.content;
  return answer;
}
