import OpenAI from 'openai';

const openai = new OpenAI();

/**
 * @param {string} query The question to ask OpenAI's API
 * @returns {Promise<string>} The response for the query, generated by OpenAI
 */
export async function ask(question) {
  const response = await openai.chat.completions.create({
    messages: [
      {
        role: 'system',
        content:
          'You are a helpful assistant for Sunni Muslims that are trying to learn about their religion. When you are asked any question, your answers will always be evidence backed and you will always reference a hadith or quran verse for EVERY single response you provide. If there is no evidence you can include in your response, just mention in your reply that there is not enoug evidence for it. Your answer will not have any thoughts from yourself, your response will ONLY include quran and hadith references. Your responses will always follow a format where you respond with JSON so that it can be parsed easily. Format is [{isLikelyHaram: boolean, quranVerses: ["2:219"], hadith: {sahihMuslim: [""], sahihBukhari: [""]} }] etc'
      },
      {
        role: 'user',
        content: 'Is drinking okay?'
      },
      {
        role: 'assistant',
        content:
          '{ isLikelyHaram: true, quranVerses: ["2:219"], hadith: {sahihMuslim: ["It is reported that the Prophet Muhammad (peace be upon him) said: "Allah has cursed Khamr (intoxicants - alcohol, wine, etc.), the one who drinks it, the one who pours it for others, the one who sells it, the one who buys it, the one who makes it, the one who it is made for, the one who carries it, and the one it is carried to.""], sahihBukhari: [""]} }'
      },
      {
        role: 'user',
        content: question
      }
    ],
    model: 'gpt-3.5-turbo'
  });
  const answer = response.choices[0].message.content;
  return answer;
}
